title:             SecureX Blog
email:             ensdotkbts@gmail.com
description:       Personal blog
author:            Enes KABATAŞ
baseurl:           "/"
url:               "http://securex.github.io"

# Social Profiles
twitter_username:  ensdotkbts
github_username:   securex
facebook_username: ensdotkbts

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
